"""Report component and section-building helpers."""

from mmsr.report.components import (
    CommentaryBlock,
    Heatmap,
    HeatmapCell,
    HtmlBlock,
    MetricCard,
    MetricTable,
    MetricTableRow,
    PlotlyChart,
    ReportBranding,
    ReportDocument,
    ReportPage,
    TimeSeriesChart,
    TimeSeriesChartPoint,
)
from mmsr.report.drilldowns import (
    DEFAULT_DRILLDOWN_GROUP_KEYS,
    DrilldownReportPageOptions,
    DrilldownSelectionOptions,
    build_drilldown_report_page,
    drilldown_scope_key,
    select_drilldown_comparisons,
)
from mmsr.report.market_report import (
    MarketReportInput,
    MarketReportOptions,
    build_market_monitor_report,
)
from mmsr.report.metric_docs import (
    MetricDefinitionsAppendixOptions,
    append_metric_definitions_appendix,
    build_metric_definitions_appendix_page,
    collect_metric_definitions_from_pages,
    metric_definitions_markdown,
)
from mmsr.report.overview import (
    ExecutiveOverviewOptions,
    build_executive_market_overview_block,
)
from mmsr.report.sections import (
    ComparisonSectionOptions,
    build_activity_intraday_distribution_chart,
    build_comparison_metric_table,
    build_comparison_report_page,
    build_heatmap,
    build_reference_target_intraday_profile_chart,
    build_time_series_chart,
)

from mmsr.report.toxicity import (
    DEFAULT_REVERSION_HORIZON_ORDER,
    DEFAULT_REVERSION_VENUE_ORDER,
    DEFAULT_TOXICITY_CONTEXT_RANKING,
    TOXICITY_CONTEXT_RANKINGS,
    ToxicityContextRanking,
    ToxicityReversionPageOptions,
    build_toxicity_reversion_page,
)

from mmsr.report.symbols import (
    DEFAULT_SYMBOL_GROUP_KEYS,
    SymbolAnomalyPageOptions,
    SymbolDetailIndexOptions,
    SymbolDetailPageOptions,
    build_symbol_anomaly_page,
    build_symbol_detail_index_block,
    build_symbol_detail_pages,
    select_symbol_anomalies,
    symbol_detail_anchor_id,
)

__all__ = [
    "CommentaryBlock",
    "ComparisonSectionOptions",
    "DEFAULT_DRILLDOWN_GROUP_KEYS",
    "build_toxicity_reversion_page",
    "ToxicityReversionPageOptions",
    "DEFAULT_REVERSION_VENUE_ORDER",
    "DEFAULT_REVERSION_HORIZON_ORDER",
    "DEFAULT_TOXICITY_CONTEXT_RANKING",
    "TOXICITY_CONTEXT_RANKINGS",
    "ToxicityContextRanking",
    "DrilldownReportPageOptions",
    "DrilldownSelectionOptions",
    "DEFAULT_SYMBOL_GROUP_KEYS",
    "ExecutiveOverviewOptions",
    "Heatmap",
    "HeatmapCell",
    "HtmlBlock",
    "MetricCard",
    "MetricTable",
    "MetricTableRow",
    "PlotlyChart",
    "TimeSeriesChart",
    "TimeSeriesChartPoint",
    "MetricDefinitionsAppendixOptions",
    "MarketReportInput",
    "MarketReportOptions",
    "ReportBranding",
    "SymbolAnomalyPageOptions",
    "SymbolDetailIndexOptions",
    "SymbolDetailPageOptions",
    "ReportDocument",
    "ReportPage",
    "append_metric_definitions_appendix",
    "build_activity_intraday_distribution_chart",
    "build_comparison_metric_table",
    "build_comparison_report_page",
    "build_drilldown_report_page",
    "build_executive_market_overview_block",
    "build_heatmap",
    "build_reference_target_intraday_profile_chart",
    "build_market_monitor_report",
    "build_metric_definitions_appendix_page",
    "build_symbol_anomaly_page",
    "build_symbol_detail_index_block",
    "build_symbol_detail_pages",
    "build_time_series_chart",
    "drilldown_scope_key",
    "collect_metric_definitions_from_pages",
    "metric_definitions_markdown",
    "select_symbol_anomalies",
    "select_drilldown_comparisons",
    "symbol_detail_anchor_id",
]
