repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML]
        pass_filenames: false
        args:
          - --config-file=pyproject.toml
          - --disable-error-code=attr-defined
          - --disable-error-code=no-any-return
          - --disable-error-code=arg-type
          - --disable-error-code=return-value
          - --disable-error-code=operator
          - --disable-error-code=assignment
          - --disable-error-code=misc
          - --disable-error-code=name-defined
          - --ignore-missing-imports
          - mmsr
  - repo: local
    hooks:
      - id: pytest-full
        name: pytest-full
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
