site_name: mmsr
theme:
  name: material
plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
  - kdb integration testing: kdb_integration_testing.md
  - Production readiness checklist: production_readiness.md
