[tox]
envlist = py312, py313, lint, docs
isolated_build = true

[testenv]
allowlist_externals = poetry
commands_pre = poetry install --with dev
commands = poetry run pytest

[testenv:lint]
allowlist_externals = poetry
commands_pre = poetry install --with dev
commands =
    poetry run black --check mmsr tests
    poetry run isort --check-only mmsr tests
    poetry run flake8 mmsr tests
    poetry run mypy mmsr


[testenv:docs]
allowlist_externals = poetry
commands_pre = poetry install --with doc
commands = poetry run mkdocs build --strict
