"""Starter metric definitions."""

from __future__ import annotations

from mmsr.metrics.base import MetricDefinition

STARTER_METRICS: list[MetricDefinition] = [
    MetricDefinition(
        name="turnover",
        label="Turnover",
        category="Activity",
        description="Total traded notional over the selected period or bucket.",
        formula="sum(trade_price * trade_size)",
        interpretation="Higher turnover indicates more trading activity.",
        unit="JPY",
        higher_is_better=None,
        default_aggregation="sum",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["trades"],
        required_columns=["trade_price", "trade_size"],
        caveats=["Auction and off-market prints may need explicit filtering."],
    ),
    MetricDefinition(
        name="volume",
        label="Volume",
        category="Activity",
        description="Total traded shares over the selected period or bucket.",
        formula="sum(trade_size)",
        interpretation="Higher volume indicates more share trading activity.",
        unit="shares",
        higher_is_better=None,
        default_aggregation="sum",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["trades"],
        required_columns=["trade_size"],
    ),
    MetricDefinition(
        name="trade_count",
        label="Trade Count",
        category="Activity",
        description="Number of trades over the selected period or bucket.",
        formula="count trades",
        interpretation="Higher trade count indicates more frequent trading.",
        unit="count",
        higher_is_better=None,
        default_aggregation="sum",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["trades"],
        required_columns=["trade_time"],
    ),
    MetricDefinition(
        name="quoted_spread_bps",
        label="Quoted Spread",
        category="Liquidity",
        description="Best ask minus best bid, normalized by mid price.",
        formula="10000 * (ask_price - bid_price) / ((ask_price + bid_price) / 2)",
        interpretation="Higher values usually indicate worse liquidity and higher immediate transaction cost.",
        unit="bps",
        higher_is_better=False,
        default_aggregation="median",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["quotes"],
        required_columns=["bid_price", "ask_price"],
        caveats=["Can be distorted by stale, crossed, or locked quotes."],
    ),
    MetricDefinition(
        name="quoted_spread_ticks",
        label="Quoted Spread in Ticks",
        category="Liquidity",
        description="Best ask minus best bid, normalized by the applicable tick size.",
        formula="(ask_price - bid_price) / tick_size",
        interpretation="Useful for comparing spread behavior across Japanese names with different tick-size ladders.",
        unit="ticks",
        higher_is_better=False,
        default_aggregation="median",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["quotes", "symbols"],
        required_columns=["bid_price", "ask_price", "tick_size"],
    ),
    MetricDefinition(
        name="top_of_book_depth",
        label="Top-of-Book Depth",
        category="Liquidity",
        description="Visible size at the best bid and best ask.",
        formula="bid_size + ask_size",
        interpretation="Higher values usually indicate more immediately available liquidity.",
        unit="shares",
        higher_is_better=True,
        default_aggregation="median",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["quotes"],
        required_columns=["bid_size", "ask_size"],
    ),
    MetricDefinition(
        name="realized_volatility",
        label="Realized Volatility",
        category="Volatility",
        description="Volatility of mid-price returns within the selected bucket.",
        formula="std(log(mid_price) - prev(log(mid_price)))",
        interpretation="Higher values indicate more price instability.",
        unit="bps or decimal",
        higher_is_better=False,
        default_aggregation="custom",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["quotes"],
        required_columns=["bid_price", "ask_price"],
    ),
    MetricDefinition(
        name="effective_spread_bps",
        label="Effective Spread",
        category="Transaction Cost",
        description="Estimated actual execution cost relative to the prevailing mid price.",
        formula="2 * abs(trade_price - mid_before_trade) / mid_before_trade * 10000",
        interpretation="Higher values indicate higher realized trading cost.",
        unit="bps",
        higher_is_better=False,
        default_aggregation="median",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["trades", "quotes"],
        required_columns=["trade_price", "bid_price", "ask_price"],
        caveats=["Requires correct trade-to-quote alignment."],
    ),
    MetricDefinition(
        name="price_impact_30s_bps",
        label="Price Impact 30s",
        category="Transaction Cost",
        description="Post-trade mid-price movement in the direction of the inferred aggressor side.",
        formula="side * (mid_after_30s - mid_before_trade) / mid_before_trade * 10000",
        interpretation="Higher values indicate stronger adverse selection or market impact.",
        unit="bps",
        higher_is_better=False,
        default_aggregation="median",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["trades", "quotes"],
        required_columns=["trade_price", "bid_price", "ask_price"],
        caveats=["Requires trade signing and horizon-specific quote alignment."],
    ),
    MetricDefinition(
        name="signed_turnover",
        label="Signed Turnover",
        category="Flow",
        description="Buy-initiated notional minus sell-initiated notional.",
        formula="sum(side * trade_price * trade_size)",
        interpretation="Positive values indicate net buyer-initiated pressure; negative values indicate seller-initiated pressure.",
        unit="JPY",
        higher_is_better=None,
        default_aggregation="sum",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["trades", "quotes"],
        required_columns=["trade_price", "trade_size", "bid_price", "ask_price"],
        caveats=["Depends on trade signing quality."],
    ),
    MetricDefinition(
        name="trade_imbalance",
        label="Trade Imbalance",
        category="Flow",
        description="Signed volume normalized by total volume.",
        formula="sum(side * trade_size) / sum(trade_size)",
        interpretation="Values near 1 indicate buyer-initiated dominance; values near -1 indicate seller-initiated dominance.",
        unit="ratio",
        higher_is_better=None,
        default_aggregation="custom",
        supports_intraday=True,
        supports_symbol_level=True,
        required_tables=["trades", "quotes"],
        required_columns=["trade_size", "trade_price", "bid_price", "ask_price"],
    ),
]

PRIMARY_QUOTE_REVERSION_HORIZONS: tuple[tuple[str, str], ...] = (
    ("10ms", "+10ms Reversion"),
    ("100ms", "+100ms Reversion"),
    ("500ms", "+500ms Reversion"),
    ("1s", "+1s Reversion"),
    ("5s", "+5s Reversion"),
    ("10s", "+10s Reversion"),
)

for horizon, label in PRIMARY_QUOTE_REVERSION_HORIZONS:
    metric_safe_horizon = horizon.replace("ms", "ms").replace("s", "s")
    STARTER_METRICS.append(
        MetricDefinition(
            name=f"primary_quote_reversion_{metric_safe_horizon}_bps",
            label=label,
            category="Toxicity",
            description=(
                "Signed movement of the primary exchange mid price from the "
                f"prevailing mid before an aggressive venue trade to {horizon} "
                "after the trade."
            ),
            formula=(
                "side * 10000 * (primary_mid[t + horizon] - "
                "primary_mid[t-]) / primary_mid[t-]"
            ),
            interpretation=(
                "Positive values mean the primary mid moved in the aggressive "
                "trade direction, suggesting greater adverse selection or "
                "toxicity. Negative values mean the initial trade direction "
                "reverted at the selected horizon."
            ),
            unit="bps",
            higher_is_better=False,
            default_aggregation="notional_weighted_mean",
            supports_intraday=True,
            supports_symbol_level=True,
            required_tables=["venue_trades", "primary_quotes"],
            required_columns=[
                "trade_time",
                "venue",
                "trade_price",
                "trade_size",
                "aggressor_side",
                "primary_bid_price",
                "primary_ask_price",
            ],
            caveats=[
                "Requires accurate aggressor-side classification.",
                "Short horizons such as 10ms and 100ms are sensitive to timestamp synchronization and feed latency.",
                "Results should be filtered for stale, crossed, locked, or unavailable primary quotes.",
                "Small sample sizes by venue, symbol, or bucket should be flagged in the report.",
            ],
        )
    )
